In [ ]:
import torch
print("✅ CUDA available:", torch.cuda.is_available())
print("🖥️ Device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

# Mount Drive (if not done yet)
from google.colab import drive
drive.mount('/content/drive')

✅ CUDA available: True
🖥️ Device: cuda
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Repeat Article Results

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP1

# [[98  4]
#  [28 21]]
# 平均准确率: 0.79
# 平均精确率: 0.77
# 平均召回率: 0.79
# 平均F1: 0.75

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(0): 88, np.int64(1): 47}
1 训练数据量: 5
1 验证数据量: 1
———————————————— tensor(87.5000, device='cuda:0')
/usr/local/lib/python3.12/dist-packages

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP2

# [[93  9]
#  [28 21]]
# 平均准确率: 0.75
# 平均精确率: 0.74
# 平均召回率: 0.75
# 平均F1: 0.71

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./"

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  20
	Batch size:             121
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.1
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             1
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64(1): 291, np.int64(0): 492}
1 训练数据量: 7
1 验证数

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_and_SP1

# [[96  6]
#  [32 17]]
# 平均准确率: 0.75
# 平均精确率: 0.70
# 平均召回率: 0.75
# 平均F1: 0.69

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./"

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/SP2_and_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  20
	Batch size:             121
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.1
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             1
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx
训练集类别分布: {np.int64(0): 594, np.int64(1): 340}
1 训练数

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1

# [[102   0]
#  [ 12  37]]
# 平均准确率: 0.92
# 平均精确率: 0.94
# 平均召回率: 0.92
# 平均F1: 0.91


!rm -f /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1/CharLSTM_best.pth.tar
!rm -f /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1/fine_CharLSTM_best.pth.tar

# 🔁 Pretrain and Finetune LSTM in one go
!python3 pretrain_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

!python3 finetune_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--fine_model_path "./fine_CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22
1 验证数据量: 3
———————————————— tensor(89.8734

# Alexey Dataset ( BSP1 )

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP1

# [[101  12]
#  [  6  29]]
# 平均准确率: 0.88
# 平均精确率: 0.88
# 平均召回率: 0.88
# 平均F1: 0.87

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 30, np.int64(0): 103}
1 训练数据量: 5
1 验证数据量: 1
———————————————— tensor(86.6667, device='cuda:0')
Fold 1: Done
1 准确率: 0.87
1 精确率: 0.87


In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP2

# [[111   2]
#  [ 27   8]]
# 平均准确率: 0.80
# 平均精确率: 0.75
# 平均召回率: 0.80
# 平均F1: 0.75

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  20
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64(1): 291, np.int64(0): 492}
1 训练数据量: 25
1

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1

# [[108   5]
#  [  3  32]]
# 平均准确率: 0.95
# 平均精确率: 0.96
# 平均召回率: 0.95
# 平均F1: 0.95


!rm -f /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1/CharLSTM_best.pth.tar
!rm -f /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1/fine_CharLSTM_best.pth.tar

# 🔁 Pretrain and Finetune LSTM in one go
!python3 pretrain_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

!python3 finetune_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--fine_model_path "./fine_CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22
1 验证数据量: 3
———————————————— tensor(89.873

# BSP2 Dataset

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP2

# [[108   5]
#  [ 23  12]]
# 平均准确率: 0.81
# 平均精确率: 0.77
# 平均召回率: 0.81
# 平均F1: 0.77

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  20
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
训练集类别分布: {np.int64(1): 54, np.int64(0): 183}
1 训练数据量: 8
1 

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1

# [[97 16]
#  [ 1 34]]
# 平均准确率: 0.88
# 平均精确率: 0.93
# 平均召回率: 0.88
# 平均F1: 0.89

# 🔁 Pretrain and Finetune LSTM in one go
!python3 pretrain_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

!python3 finetune_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--fine_model_path "./fine_CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 48, np.int64(0): 165}
1 训练数据量: 7
1 验证数据量: 1
———————————————— tensor(91.6667

# BSP3 Dataset

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/only_SP2

# [[110   3]
#  [ 30   5]]
# 平均准确率: 0.78
# 平均精确率: 0.65
# 平均召回率: 0.78
# 平均F1: 0.70

!python3 train_LSTM.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  20
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
训练集类别分布: {np.int64(1): 240, np.int64(0): 398}
1 训练数据量: 20


In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1

# [[105   8]
#  [ 10  25]]
# 平均准确率: 0.88
# 平均精确率: 0.90
# 平均召回率: 0.88
# 平均F1: 0.87

# 🔁 Pretrain and Finetune LSTM in one go
!python3 pretrain_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2

!python3 finetune_LSTM.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharLSTM_best.pth.tar" \
--fine_model_path "./fine_CharLSTM_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--hidden_dim 32 \
--num_layers 2 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/LSTM/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharLSTM_best.pth.tar
	Num classes:            2
	Num layers:             2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 213, np.int64(0): 361}
1 训练数据量: 18
1 验证数据量: 2
———————————————— tensor(84.37