In [ ]:
import torch
print("✅ CUDA available:", torch.cuda.is_available())
print("🖥️ Device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

# Mount Drive (if not done yet)
from google.colab import drive
drive.mount('/content/drive')

✅ CUDA available: True
🖥️ Device: cuda
Mounted at /content/drive


# Repeat Article Results

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1

# [[95  7]
#  [12 37]]
# 平均准确率: 0.87
# 平均精确率: 0.89
# 平均召回率: 0.87
# 平均F1: 0.87

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP1/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 64 \
--optimizer Adam \
--max_norm 400 \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.3 \
--embedding_dim 8 \
--max_length 50 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1
🔹 Running in Google Colab
in collab

Configuration:
	T max:                  60
	Batch size:             64
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.3
	Embedding dim:          8
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(0): 88, np.int64(1): 47}
1 训练数据量: 3
1 验证数据量: 1
———————————————— tensor(93.7500, device='cuda:0')
Fold 1: Done
1 准确率: 0.88
1 精确率: 0.88
1 召回率: 0.88
1 F1: 0.88

训练集类别分布: {np.int64(0): 94, np.int64(1): 42}
2 训练数据量: 3
2 验证数据量:

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2

# [[75 27]
#  [29 20]]
# 平均准确率: 0.63
# 平均精确率: 0.65
# 平均召回率: 0.63
# 平均F1: 0.62

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP2/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 500 \
--batch_size 32 \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 500
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64(1): 291, np.int64(0): 492}
1 训练数据量: 25
1 验证数据量: 1
———————————————— tensor(87.5000, device='cud

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_and_SP1

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/SP2_and_SP1/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--dropout 0.3 \
--embedding_dim 16 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_and_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  50
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.3
	Embedding dim:          16
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx
训练集类别分布: {np.int64(0): 594, np.int64(1): 340}
1 训练数据量: 30
1 验证数据量: 1
———————————————— tensor(87.5000,

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1

# 🔁 Pretrain and Finetune CNN in one go
!python3 pretrain_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

!python3 finetune_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--pre_model_path "./CharCNN_best.pth.tar" \
--fine_model_path "./fine_CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22
1 验证数据量: 3
———————————————— tensor(96.2025, device='cuda:0')
Fold 1:

# Alexey Dataset ( BSP1 )

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1

# [[101  12]
#  [  2  33]]
# 平均准确率: 0.91
# 平均精确率: 0.93
# 平均召回率: 0.91
# 平均F1: 0.91

!python3 train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--saved_values_path "./saved_values.xlsx" \
--lr_min 0.0001 \
--epochs 500 \
--batch_size 32

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.3
	Embedding dim:          8
	Epochs:                 500
	Log result:             True
	Lr:                     0.05
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 30, np.int64(0): 103}
1 训练数据量: 5
1 验证数据量: 1
———————————————— tensor(93.3333, device='cuda:0')
Fold 1: Done
1 准确率: 0.87
1 精确率: 0.90
1 召回率: 0.87
1 F1: 0.87

训练集类别分布: {np.int64(1): 30, np.i

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1

# [[97 16]
#  [ 6 29]]
# 平均准确率: 0.85
# 平均精确率: 0.88
# 平均召回率: 0.85
# 平均F1: 0.86

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP1/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 64 \
--optimizer Adam \
--max_norm 400 \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.3 \
--embedding_dim 8 \
--max_length 50 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             64
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.3
	Embedding dim:          8
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 30, np.int64(0): 103}
1 训练数据量: 3
1 验证数据量: 1
———————————————— tensor(86.6667, device='cuda:0')
Fold 1: Done
1 准确率: 0.87
1 精确率: 0.90
1 召回率: 0.87
1 F1: 0.87

训练集类别分布: {np.int64(1): 30, np

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2

# [[92 21]
#  [20 15]]
# 平均准确率: 0.72
# 平均精确率: 0.75
# 平均召回率: 0.72
# 平均F1: 0.71

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP2/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 500 \
--batch_size 32 \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 500
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64(1): 291, np.int64(0): 492}
1 训练数据量: 25
1 验证数据量: 1
———————————————— tensor(73.3333, device='cu

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1

# [[100  13]
#  [  5  30]]
# 平均准确率: 0.88
# 平均精确率: 0.90
# 平均召回率: 0.88
# 平均F1: 0.88

# 🔁 Pretrain and Finetune CNN in one go
!python3 pretrain_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

!python3 finetune_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--pre_model_path "./CharCNN_best.pth.tar" \
--fine_model_path "./fine_CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22
1 验证数据量: 3
———————————————— tensor(96.2025, device='cuda:0')
Fold 1

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2

# [[97 16]
#  [27  8]]
# 平均准确率: 0.71
# 平均精确率: 0.69
# 平均召回率: 0.71
# 平均F1: 0.68

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP2/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 500 \
--batch_size 32 \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 500
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
训练集类别分布: {np.int64(1): 54, np.int64(0): 183}
1 训练数据量: 8
1 验证数据量: 1
———————————————— tensor(73.3333, device='cud

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1

# [[101  12]
#  [  4  31]]
# 平均准确率: 0.89
# 平均精确率: 0.91
# 平均召回率: 0.89
# 平均F1: 0.90

!python3 pretrain_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 32 \
--num_classes 2

!python3 finetune_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--pre_model_path "./CharCNN_best.pth.tar" \
--fine_model_path "./fine_CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 32 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          32
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 48, np.int64(0): 165}
1 训练数据量: 7
1 验证数据量: 1
———————————————— tensor(87.5000, device='cuda:0')
Fold 1:

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2

# [[81 32]
#  [20 15]]
# 平均准确率: 0.65
# 平均精确率: 0.71
# 平均召回率: 0.65
# 平均F1: 0.67

!python3 /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/only_SP2/train_CNN.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 500 \
--batch_size 32 \
--lr_min 0.0001 \
--embedding_dim 16

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.3
	Embedding dim:          16
	Epochs:                 500
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
训练集类别分布: {np.int64(1): 240, np.int64(0): 398}
1 训练数据量: 20
1 验证数据量: 1
———————————————— tensor(73.3333, device='c

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1

# [[109   4]
#  [  3  32]]
# 平均准确率: 0.95
# 平均精确率: 0.96
# 平均召回率: 0.95
# 平均F1: 0.95

!python3 pretrain_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharCNN_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--num_classes 2

!python3 finetune_CNN.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--pre_model_path "./CharCNN_best.pth.tar" \
--fine_model_path "./fine_CharCNN_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--lr_min 0.0001 \
--T_max 60 \
--dropout 0.2 \
--embedding_dim 16 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3 \
--num_classes 2

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/CNN/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Dropout:                0.2
	Embedding dim:          16
	Epochs:                 300
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.0001
	Max length:             50
	Max norm:               400
	Model path:             ./CharCNN_best.pth.tar
	Num classes:            2
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 213, np.int64(0): 361}
1 训练数据量: 18
1 验证数据量: 2
———————————————— tensor(93.7500, device='cuda:0')
Fold 