In [ ]:
import torch
print("✅ CUDA available:", torch.cuda.is_available())
print("🖥️ Device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

# Mount Drive (if not done yet)
from google.colab import drive
drive.mount('/content/drive')

✅ CUDA available: True
🖥️ Device: cuda
Mounted at /content/drive


# Repeat Article Results

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP1

# [[92 10]
#  [19 30]]
# 平均准确率: 0.81
# 平均精确率: 0.81
# 平均召回率: 0.81
# 平均F1: 0.80

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 3 \
--hidden_dim 32 \
--num_heads 4

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP1
🔹 Running in Google Colab
in collab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     3
	Num heads:              4
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(0): 88, np.int64(1): 47}
1 训练数据量: 5
1 验证数据量: 1
———————————————— tensor(87.5000, device='cuda:0')
/usr/local/lib/python3.11/dist

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP2

# [[80 22]
#  [26 23]]
# 平均准确率: 0.68
# 平均精确率: 0.69
# 平均召回率: 0.68
# 平均F1: 0.66

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./"

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP2
🔹 Running in Google Colab
in collab
Directory already exists.

Configuration:
	T max:                  100
	Batch size:             72
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.1
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64(1): 291, np.int64(0): 492}
1 训练数据量

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/SP2_and_SP1

# [[90 12]
#  [33 16]]
# 平均准确率: 0.70
# 平均精确率: 0.70
# 平均召回率: 0.70
# 平均F1: 0.67

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./"

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/SP2_and_SP1
🔹 Running in Google Colab
in collab
Directory already exists.

Configuration:
	T max:                  50
	Batch size:             60
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.1
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1_and_SP2.xlsx
训练集类别分布: {np.int64(0): 594, np.int64(1): 34

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1

# [[96  6]
#  [37 12]]
# 平均准确率: 0.71
# 平均精确率: 0.74
# 平均召回率: 0.71
# 平均F1: 0.66

# 🔁 Pretrain and Finetune Transformer in one go
!python3 pretrain_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--embedding_dim 16 \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4

!python3 finetune_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--fine_model_path "./fine_CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--embedding_dim 16 \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          16
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22


# Alexey Dataset ( BSP1 )

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP1

# [[102  11]
#  [ 12  23]]
# 平均准确率: 0.84
# 平均精确率: 0.85
# 平均召回率: 0.84
# 平均F1: 0.83

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 3 \
--hidden_dim 32 \
--num_heads 4

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP1
🔹 Running in Google Colab
in collab
Directory already exists.

Configuration:
	T max:                  60
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     3
	Num heads:              4
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 30, np.int64(0): 103}
1 训练数据量: 5
1 验证数据量: 1
———————————————— tensor(80.0000, device='cuda:0')
Fold 1: Done
1 准确率: 0.80
1 精

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP2

# [[86 27]
#  [26  9]]
# 平均准确率: 0.64
# 平均精确率: 0.67
# 平均召回率: 0.64
# 平均F1: 0.64

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 400 \
--batch_size 32 \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  100
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 400
	Hidden dim:             12
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              SGD
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
训练集类别分布: {np.int64

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1

# [[98 15]
#  [22 13]]
# 平均准确率: 0.75
# 平均精确率: 0.77
# 平均召回率: 0.75
# 平均F1: 0.71

!python3 pretrain_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4

!python3 finetune_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--fine_model_path "./fine_CharTransformer_best_SP2TOBSP1.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/SP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 265, np.int64(0): 439}
1 训练数据量: 22


# BSP2 Dataset

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP2

# [[94 19]
#  [25 10]]
# 平均准确率: 0.70
# 平均精确率: 0.68
# 平均召回率: 0.70
# 平均F1: 0.69

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 3 \
--hidden_dim 32 \
--num_heads 4

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  100
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     3
	Num heads:              4
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
训练集类别分布: {np.int

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1

# [[84 29]
#  [13 22]]
# 平均准确率: 0.71
# 平均精确率: 0.77
# 平均召回率: 0.71
# 平均F1: 0.72

!python3 pretrain_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4

!python3 finetune_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--fine_model_path "./fine_CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP2.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 48, np.int64(0): 165}
1 训练数据量: 7
1

# BSP3 Dataset

In [ ]:
# Move to the folder
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/only_SP2

# [[89 24]
#  [18 17]]
# 平均准确率: 0.72
# 平均精确率: 0.78
# 平均召回率: 0.72
# 平均F1: 0.72

!python3 train_Transformer.py \
--train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--test_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 3 \
--hidden_dim 32 \
--num_heads 4

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/only_SP2
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  100
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             32
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     3
	Num heads:              4
	Optimizer:              Adam
	Save folder:            ./
	Saved values path:      ./saved_values.xlsx
	Test path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
	Train path:             /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
训练集类别分布: {np.int

In [ ]:
# Move to the working directory
%cd /content/drive/MyDrive/Colab\ Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1

# [[86 27]
#  [ 5 30]]
# 平均准确率: 0.78
# 平均精确率: 0.85
# 平均召回率: 0.78
# 平均F1: 0.80

!python3 pretrain_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--save_folder "./" \
--lr 0.001 \
--epochs 300 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4

!python3 finetune_Transformer.py \
--pre_train_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx" \
--tune_path "/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx" \
--model_path "./CharTransformer_best.pth.tar" \
--fine_model_path "./fine_CharTransformer_best.pth.tar" \
--saved_values_path "./saved_values.xlsx" \
--lr 0.001 \
--epochs 200 \
--batch_size 32 \
--optimizer Adam \
--num_encoder_layers 2 \
--hidden_dim 12 \
--num_heads 4 \
--unfreeze_after_epochs 100 \
--tuning_strategy 3

/content/drive/MyDrive/Colab Notebooks/repo/SP_designer/classification/Transformer/SP2_trans_SP1
🔹 Running in Google Colab
Matplotlib backend set to 'Agg' for Colab
Directory already exists.

Configuration:
	T max:                  57
	Batch size:             32
	Checkpoint:             True
	Device:                 cuda
	Embedding dim:          8
	Epochs:                 300
	Hidden dim:             12
	Log result:             True
	Lr:                     0.001
	Lr min:                 0.001
	Max length:             50
	Max norm:               400
	Model path:             ./CharTransformer_best.pth.tar
	Num classes:            2
	Num encoder layers:     2
	Num heads:              4
	Optimizer:              Adam
	Pre train path:         /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP3.xlsx
	Save folder:            ./
	Tune path:              /content/drive/MyDrive/Colab Notebooks/repo/SP_designer/data/BSP1.xlsx
训练集类别分布: {np.int64(1): 213, np.int64(0): 361}
1 训练数据量: 18